#!/bin/bash

source hooks/config.sh

for arch in $ARCHS; do
	BASE_IMAGE_PREFIX="${base_image_prefix_map[${arch}]}"
	ARCH_SUFFIX="${tag_suffix_map[${arch}]}"
	QEMU_ARCH="${docker_qemu_arch_map[${arch}]}"
	docker build \
		--build-arg BASE_IMAGE_PREFIX=${BASE_IMAGE_PREFIX} \
		--build-arg ARCH=${QEMU_ARCH} \
		--file $DOCKERFILE_PATH \
		--tag "${IMAGE_NAME}-${ARCH_SUFFIX}" \
		.
done
