#!/bin/bash

source hooks/config.sh

for arch in $ARCHS; do
	BASE_IMAGE_PREFIX="${base_image_prefix_map[${arch}]}"
	ARCH=$arch
	docker build \
		--build-arg BASE_IMAGE_PREFIX=${BASE_IMAGE_PREFIX} \
		--build-arg ARCH=${ARCH} \
		--file $DOCKERFILE_PATH \
		--tag "${IMAGE_NAME}-${ARCH}"  \
		.
done
