#!/bin/bash

source hooks/config.sh

IMAGE_NAME="${IMAGE_NAME//index.docker.io\/}"
MANIFESTS=""
for arch in ${ARCHS}; do
	docker push ${IMAGE_NAME}-${arch}
	MANIFESTS="${MANIFESTS} ${IMAGE_NAME}-${arch}"
done

docker manifest create ${IMAGE_NAME} $MANIFESTS

for arch in ${ARCHS}; do
	docker manifest annotate ${IMAGE_NAME} ${IMAGE_NAME}-${arch} \
	--os linux \
	--arch "${arch_to_manifest_map[${arch}]}" \
	--variant "${arch_to_variant_map[${arch}]}"
done

#docker manifest push --purge "${IMAGE_NAME}"
